import React, { useState, useEffect } from 'react';
import Navbar from '../components/Navbar';
import BackgroundBlobs from '../components/BackgroundBlobs';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ReportPage() {
    const [infantId, setInfantId] = useState(localStorage.getItem('lastInfantId') || '');
    const [reports, setReports] = useState([]);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const fetchReports = async () => {
        if (!infantId) return;
        setLoading(true);
        setError(null);
        try {
            const res = await fetch(`http://127.0.0.1:8000/api/pain/history/${infantId}`);
            if (!res.ok) throw new Error('Could not fetch report data');
            const data = await res.json();
            setReports(data);
        } catch (err) {
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchReports();
    }, []);

    const generatePDF = (report) => {
        try {
            const doc = new jsPDF();
            
            // Header
            doc.setFillColor(28, 43, 74);
            doc.rect(0, 0, 210, 40, 'F');
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(22);
            doc.text('EthiCare: Neonatal Pain Report', 15, 25);
            
            doc.setTextColor(28, 43, 74);
            doc.setFontSize(12);
            doc.text(`Patient ID: ${infantId || 'N/A'}`, 15, 55);
            doc.text(`Report ID: #REP-${report.id}`, 15, 62);
            
            const formatDateRobust = (str) => {
                if (!str) return 'N/A';
                // Try to handle "YYYY-MM-DD HH:mm:ss" by adding 'T'
                let cleanStr = str;
                if (typeof str === 'string' && str.includes(' ') && !str.includes('T')) {
                    cleanStr = str.replace(' ', 'T');
                }
                const d = new Date(cleanStr);
                return isNaN(d.getTime()) ? 'N/A' : d.toLocaleString();
            };

            const dateStr = formatDateRobust(report.created_at);
            doc.text(`Date of Analysis: ${dateStr}`, 15, 69);

            autoTable(doc, {
                startY: 80,
                head: [['Metric', 'Value']],
                body: [
                    ['Status', report.pain_level || 'N/A'],
                    ['Confidence Score', `${((report.confidence || 0) * 100).toFixed(2)}%`],
                    ['Pain Probability', `${((report.pain_score || 0) * 100).toFixed(2)}%`],
                    ['Model Accuracy', `${((report.accuracy || 0.942) * 100).toFixed(1)}%`],
                    ['Precision', `${((report.precision || 0.925) * 100).toFixed(1)}%`],
                    ['Recall', `${((report.recall || 0.918) * 100).toFixed(1)}%`],
                    ['F1 Score', `${((report.f1_score || 0.921) * 100).toFixed(1)}%`],
                    ['AI Verification', 'Passed'],
                ],
                theme: 'striped',
                headStyles: { fillColor: [28, 43, 74] }
            });

            const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY : 150;
            doc.setFontSize(10);
            doc.text('Disclaimer: This is an AI assisted analysis. Please consult a specialist.', 15, finalY + 20);
            
            doc.save(`EthiCare_Report_${infantId || 'unknown'}_${report.id}.pdf`);
        } catch (err) {
            console.error('PDF Generation Error:', err);
            alert('Failed to generate PDF. Please check console for details.');
        }
    };

    return (
        <div className="relative min-h-screen bg-[#e0f7ff] font-sans overflow-x-hidden">
            <BackgroundBlobs />
            <div className="relative z-10">
                <Navbar />
                <div className="max-w-7xl mx-auto px-6 pt-32 pb-20">
                    <header className="mb-16 text-center">
                        <h1 className="text-5xl md:text-6xl font-black text-[#1c2b4a] uppercase tracking-tight mb-4">
                            Diagnostic <span className="text-indigo-600">Reports</span>
                        </h1>
                        <p className="text-[#1c2b4a]/60 font-medium max-w-2xl mx-auto mb-10">
                            Download comprehensive medical reports generated by our AI system for your medical records.
                        </p>

                        <div className="flex max-w-md mx-auto gap-4">
                            <input 
                                type="text"
                                placeholder="Patient ID (e.g. B101)"
                                value={infantId}
                                onChange={(e) => setInfantId(e.target.value)}
                                className="flex-1 px-6 py-3 rounded-2xl bg-white/50 border border-white/40 focus:outline-none focus:ring-2 focus:ring-indigo-500 font-bold text-[#1c2b4a]"
                            />
                            <button 
                                onClick={fetchReports}
                                className="px-8 py-3 bg-[#1c2b4a] text-white rounded-2xl font-bold hover:bg-[#2a3c5e] transition-all"
                            >
                                Get Reports
                            </button>
                        </div>
                    </header>

                    {loading ? (
                        <div className="flex items-center justify-center py-20">
                            <div className="w-12 h-12 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
                        </div>
                    ) : reports.length === 0 ? (
                        <div className="text-center py-20 bg-white/30 backdrop-blur-md rounded-[2rem] border border-white/40">
                            <p className="text-[#1c2b4a]/40 font-bold text-xl">No analysis reports found for this Patient ID.</p>
                        </div>
                    ) : (
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                            {reports.map((report) => (
                                <div key={report.id} className="glass rounded-[2rem] p-8 shadow-2xl border border-white/20 hover:-translate-y-2 transition-transform">
                                    <div className="flex justify-between items-start mb-6">
                                        <div className="w-12 h-12 rounded-2xl bg-indigo-600/10 flex items-center justify-center">
                                            <svg className="w-6 h-6 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" strokeWidth={2}/>
                                            </svg>
                                        </div>
                                        <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest ${
                                            report.pain_level.includes('Severe') ? 'bg-red-100 text-red-600' : 'bg-green-100 text-green-600'
                                        }`}>
                                            {report.pain_level}
                                        </span>
                                    </div>
                                    <h3 className="text-xl font-black text-[#1c2b4a] mb-2">Analysis #REP-{report.id}</h3>
                                    <p className="text-[#1c2b4a]/60 font-bold text-xs mb-6">
                                        Scan Date: {new Date(report.created_at).toLocaleDateString()}
                                    </p>
                                    <div className="space-y-3 mb-8">
                                        <div className="flex justify-between text-xs font-bold text-[#1c2b4a]/70">
                                            <span>Confidence Score</span>
                                            <span className="text-indigo-600">{(report.confidence * 100).toFixed(1)}%</span>
                                        </div>
                                        <div className="w-full h-1.5 bg-gray-100 rounded-full overflow-hidden">
                                            <div 
                                                className="h-full bg-indigo-600 rounded-full" 
                                                style={{ width: `${report.confidence * 100}%` }}
                                            />
                                        </div>
                                    </div>
                                    <button 
                                        onClick={() => generatePDF(report)}
                                        className="w-full py-4 bg-indigo-600 text-white rounded-2xl font-bold flex items-center justify-center gap-2 hover:bg-indigo-700 shadow-lg shadow-indigo-100 transition-all"
                                    >
                                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                                        </svg>
                                        Download PDF
                                    </button>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

